version: '2'
services:
  bro:
    image: broker
    build: ./broker/
    expose:
      - "9998"
      - "9999"
  wor:
    image: worker
    build: ./worker/
    links:
      - bro
    environment:
      - BROKER_URL=tcp://bro:9999
