apiVersion: v1
kind: Pod
metadata:
  name: webpod
  labels:
    app: webapp
    release: "0"
spec:
  containers:
  - name: webserver
    image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: webpodnewrel
  labels:
    app: webapp
    release: "0.5"
spec:
  containers:
  - name: webserv
    image: httpd
